# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_affiliates_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliates',
            name='category',
            field=models.CharField(choices=[('1', 'Fundaciones'), ('2', 'Colaboradores'), ('3', 'Vocales')], max_length=1),
        ),
        migrations.AlterField(
            model_name='affiliates',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='affiliates',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='affiliates',
            name='image',
            field=models.ImageField(upload_to='affiliates'),
        ),
    ]
