# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_institution', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('phone_institution', models.IntegerField()),
                ('person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('confirm_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.IntegerField()),
                ('twitter', models.CharField(blank=True, max_length=255)),
                ('linkedin', models.CharField(blank=True, max_length=255)),
                ('instagram', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('num_external', models.CharField(blank=True, max_length=255)),
                ('num_internal', models.CharField(blank=True, max_length=255)),
                ('colony', models.CharField(blank=True, max_length=255)),
                ('delegation_municipality', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.IntegerField()),
                ('state', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
