# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azuldirectorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoriomodel',
            name='facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='directoriomodel',
            name='phone',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='directoriomodel',
            name='phone_institution',
            field=models.CharField(max_length=55),
        ),
    ]
