# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='GaleryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=55)),
                ('image', models.ImageField(upload_to='')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galery.ArtistModel')),
            ],
        ),
    ]
